"""Segment descriptions via a vision-language model over OpenRouter.

Reads OPENROUTER_DSN in the `openai://<key>@openrouter.ai/api/v1/<model>`
shape used across the fleet's other projects (see finradar/.env) - key and
model both live in that one string, no separate env vars to keep in sync.
One thumbnail per segment (already generated by generate_thumbnails) is
enough context for "what exercise is this" - no need to send full clips.
"""

import base64
import json
import os
import re
import urllib.request

from ..config import THUMBS_DIR
from ..db import SessionLocal
from ..models import Segment

DSN_RE = re.compile(r"^openai://([^@]+)@openrouter\.ai/api/v1/(.+)$")

PROMPT = (
    "Опиши коротко по-русски, что за упражнение делает человек на этом кадре "
    "и в какой он позе. 1-2 предложения, без вступлений."
)


def _client():
    dsn = os.environ.get("OPENROUTER_DSN")
    if not dsn:
        raise RuntimeError("OPENROUTER_DSN not set")
    m = DSN_RE.match(dsn)
    if not m:
        raise RuntimeError(f"unexpected OPENROUTER_DSN shape: {dsn[:20]}...")
    return m.group(1), m.group(2)  # key, model


def describe_image(key: str, model: str, image_path) -> str:
    img_b64 = base64.b64encode(image_path.read_bytes()).decode()
    payload = {
        "model": model,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "text", "text": PROMPT},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}},
            ],
        }],
    }
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = json.load(resp)
    return data["choices"][0]["message"]["content"].strip()


def describe_video(video_id: int) -> dict:
    """Fill `description` for every segment of a video that doesn't have one
    yet. Returns {"done": n, "skipped": n, "failed": [(segment_id, error)]}."""
    key, model = _client()
    db = SessionLocal()
    result = {"done": 0, "skipped": 0, "failed": []}
    try:
        segments = (
            db.query(Segment)
            .filter(Segment.video_id == video_id)
            .order_by(Segment.start_sec)
            .all()
        )
        for i, seg in enumerate(segments, start=1):
            if seg.description:
                result["skipped"] += 1
                continue
            thumb = THUMBS_DIR / str(video_id) / f"{i}.jpg"
            if not thumb.exists():
                result["failed"].append((seg.id, "no thumbnail"))
                continue
            try:
                seg.description = describe_image(key, model, thumb)
                db.commit()
                result["done"] += 1
            except Exception as exc:  # noqa: BLE001 - keep going on per-segment failures
                result["failed"].append((seg.id, str(exc)))
    finally:
        db.close()
    return result
