"""auth_accounts_and_audit

Revision ID: 788d5ad60bc4
Revises: f70e7970f05b
Create Date: 2026-09-16 05:06:23.543105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '788d5ad60bc4'
down_revision: Union[str, None] = 'f70e7970f05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_kind'), 'audit_events', ['actor_kind'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('staff_identities',
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('oidc_sub', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_member_id')
    )
    op.create_index(op.f('ix_staff_identities_oidc_sub'), 'staff_identities', ['oidc_sub'], unique=True)
    op.create_table('student_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_accounts_email'), 'student_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_student_accounts_student_id'), 'student_accounts', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_accounts_student_id'), table_name='student_accounts')
    op.drop_index(op.f('ix_student_accounts_email'), table_name='student_accounts')
    op.drop_table('student_accounts')
    op.drop_index(op.f('ix_staff_identities_oidc_sub'), table_name='staff_identities')
    op.drop_table('staff_identities')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_kind'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
