"""baseline

Revision ID: f70e7970f05b
Revises: 
Create Date: 2026-09-16 04:58:29.116133
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f70e7970f05b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_upload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('target_sample_fps', sa.Integer(), nullable=False),
    sa.Column('pose_model_complexity', sa.Integer(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=False),
    sa.Column('show_skeleton', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='studentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'editor', name='team_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='videostatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('track_path', sa.String(), nullable=True),
    sa.Column('frames_total', sa.Integer(), nullable=True),
    sa.Column('frames_done', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_videos',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=200), nullable=True),
    sa.Column('training_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_student_videos_student_id'), 'student_videos', ['student_id'], unique=False)
    op.create_table('video_assessments',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', name='assessmentstatus'), nullable=False),
    sa.Column('technique', sa.Integer(), nullable=True),
    sa.Column('range_of_motion', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('symmetry', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('range_of_motion IS NULL OR range_of_motion BETWEEN 1 AND 5'),
    sa.CheckConstraint('stability IS NULL OR stability BETWEEN 1 AND 5'),
    sa.CheckConstraint('symmetry IS NULL OR symmetry BETWEEN 1 AND 5'),
    sa.CheckConstraint('technique IS NULL OR technique BETWEEN 1 AND 5'),
    sa.CheckConstraint('tempo IS NULL OR tempo BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('video_publications',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_video_publications_token'), 'video_publications', ['token'], unique=True)
    op.create_table('exercises',
    sa.Column('angle_tolerance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='exercisestatus'), nullable=False),
    sa.Column('reference_segment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_segment_id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_index(op.f('ix_exercises_status'), 'exercises', ['status'], unique=False)
    op.create_table('segment_assessments',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('technique', sa.Integer(), nullable=True),
    sa.Column('range_of_motion', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('symmetry', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('range_of_motion IS NULL OR range_of_motion BETWEEN 1 AND 5'),
    sa.CheckConstraint('stability IS NULL OR stability BETWEEN 1 AND 5'),
    sa.CheckConstraint('symmetry IS NULL OR symmetry BETWEEN 1 AND 5'),
    sa.CheckConstraint('technique IS NULL OR technique BETWEEN 1 AND 5'),
    sa.CheckConstraint('tempo IS NULL OR tempo BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('segment_comparisons',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reference_segment_id', sa.Integer(), nullable=False),
    sa.Column('tempo_score', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feature_scores', sa.JSON(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segment_comparisons_exercise_id'), 'segment_comparisons', ['exercise_id'], unique=False)
    op.create_table('segment_exercises',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segment_exercises_exercise_id'), 'segment_exercises', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_exercises_exercise_id'), table_name='segment_exercises')
    op.drop_table('segment_exercises')
    op.drop_index(op.f('ix_segment_comparisons_exercise_id'), table_name='segment_comparisons')
    op.drop_table('segment_comparisons')
    op.drop_table('segment_assessments')
    op.drop_index(op.f('ix_exercises_status'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_video_publications_token'), table_name='video_publications')
    op.drop_table('video_publications')
    op.drop_table('video_assessments')
    op.drop_index(op.f('ix_student_videos_student_id'), table_name='student_videos')
    op.drop_table('student_videos')
    op.drop_table('segments')
    op.drop_table('videos')
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
